name: molslice
description: Parallelize Molecular Simulations.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.0.2 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  provider:
  url_launcher:
  flutter_linkify:
  flutter_markdown:

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0


flutter:
  uses-material-design: true
  fonts:
    - family: providence
      fonts:
        - asset: fonts/providence/Providence.ttf
    - family: enigmatic
      fonts:
        - asset: fonts/enigmatic/EnigRegu/Enigma__2.TTF
  assets:
    - ../simulation_data/case_1/system.webp
    - ../simulation_data/case_2/system.webp