name: Flutter Web
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest     
    steps:
    - uses: actions/checkout@v1
    - uses: actions/setup-java@v1
      with:
        java-version: '1.8.x'
    - uses: subosito/flutter-action@v1
      with:
        flutter-version: '3.10.x' # you can use 1.12
        channel: 'beta' # Currently you have to use beta channel for Flutter web.
    - name: Upgrades flutter
      run: flutter upgrade
      working-directory: ./web_app/
    - name: Enable Web
      run: flutter config --enable-web
      working-directory: .
    - name: Install dependencies
      run: flutter packages get
      working-directory: ./web_app/
    - name: Build Web
      run: flutter build web --release
      working-directory: ./web_app/
    - name: Deploy
      run: |
        cd web_app/build/web
        git init
        git config user.name  "md-challenge"
        git config user.email "md-challenge@proton.me"
        git remote add secure-origin https://${{ secrets.ACTIONS_TOKEN }}@github.com/md-challenge/md-challenge.github.io.git
        git checkout -b gh-pages
        git add .
        git commit -m "Updated docs"
        git push --force secure-origin gh-pages